<?php /** @var \PixelOpen\Plausible\Block\Script $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?php if ($block->isEnabled()): ?>
<script defer data-domain="<?= $block->getHost() ?>" src="<?= $escaper->escapeUrl($block->getScriptUrl()) ?>"></script>
<?php
$script = <<<script
    window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }
script;
echo /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false);
?>
<?php endif; ?>
