<?php /** @var \PixelOpen\Plausible\Block\Adminhtml\Stats $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->canShow()): ?>
    <?php if ($block->getSharedLink()): ?>
        <iframe title="plausible" plausible-embed
                src="<?= $escaper->escapeUrl($block->getSharedLink()) ?>&embed=true&theme=light" scrolling="no"
                frameborder="0" loading="lazy" style="width: 1px; min-width: 100%; height: 2100px;"></iframe>
        <script async src="<?= $escaper->escapeUrl($block->getInstanceUrl()) ?>/js/embed.host.js"></script>
    <?php else: ?>
        <div class="message message-error">
            <?= __('The Shared Link is missing or is not valid. Update it in the configuration:') ?>
            <a href="<?= $escaper->escapeUrl($block->getConfigLink()) ?>"><?= __('Plausible Configuration') ?></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
