<?php /** @var \PixelOpen\Plausible\Block\Adminhtml\Stats $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->canShow()): ?>
    <?php if ($block->getSharedLink()): ?>
        <iframe plausible-embed src="<?= $escaper->escapeUrl($block->getSharedLink()) ?>&embed=true&theme=light" scrolling="no" frameborder="0" loading="lazy" style="width: 1px; min-width: 100%; height: 2100px;"></iframe>
        <div style="font-size: 14px; padding-bottom: 14px;">Stats powered by <a target="_blank" style="color: #4F46E5; text-decoration: underline;" href="https://plausible.io">Plausible Analytics</a></div>
        <script async src="<?= $escaper->escapeUrl($block->getInstanceUrl()) ?>/js/embed.host.js"></script>
    <?php else: ?>
        <div class="message message-error">
            <?= __('The Shared Link is missing or is not valid. Update it in the configuration:') ?>
            <a href="<?= $escaper->escapeUrl($block->getConfigLink()) ?>"><?= __('Plausible Configuration') ?></a>
        </div>
    <?php endif; ?>
<?php endif; ?>
